### ISSUE TITLE
[NEED ASSIST] Redirect Components (Paypal etc) do not call didFail when dragged to dismiss

### ISSUE THREAD

**Issue by MattCheetham** [Adyen/adyen-ios#268] opened 2020-11-16 13:55 UTC
**Describe the challenge**
Using the drop-in SDK on iOS. If you have components like Paypal or Klarna enabled you can get stuck in a loading state. 

1. Initiate a payment
2. Select Paypal
3. Wait for the browser window to present
4. Drag down the browser window to dismiss
5. Notice that the dropin component is now stuck in a loading state that you cannot dismiss

If you use the "Cancel" button on the browser, didFail is called correctly. 

Some googling [suggests](https://stackoverflow.com/questions/62135577/safariviewcontrollerdidfinish-does-not-fire-when-swiping-down-to-dismiss) that you may need to become the presentation delegate to detect this situation.

Am I missing something here? Is there a way to detect a drag dismissal that I need to implement manually?

**Screenshots**
Stuck after dragging to dismiss.
![Simulator Screen Shot - iPhone 12 mini - 2020-11-16 at 13 50 28](https://user-images.githubusercontent.com/599289/99260327-224ea080-2813-11eb-9a60-7a1f4a911ab1.png)

**Comment by descorp** [comment] 2020-11-16 15:47
Hi @MattCheetham 

By design, the handling and presentation of actions is a responsibility of the merchant's (your) application.
SDK only provides helpers like `DropInActionComponent` or `RedirectComponent`.
Because of this - we are trying not to assume how it is presented and handled.

In the [sample code](https://github.com/Adyen/adyen-ios/blob/develop/Common%20Example%20code/PaymentsController.swift#L177-L191) we use `currentComponent?.stopLoading()` to stop spinner. This work for both DropIn and standalone components with RedirectActions.

I will investigate the idea of adding a presentation delegate to a RedirectComponent. 
Thank you for the feedback!

**Comment by bennibau** [comment] 2020-11-17 13:25
I have the same problem as @MattCheetham and I think he is right that we do not have access to the `WebRedirectComponent` . I @descorp is right please provide sample code how we can have access to those callbacks or where we should handle that.

**Comment by descorp** [comment] 2020-11-20 10:03
Hey @bennibau  @MattCheetham 

> Surely that's unexpected behaviour in the SDK? 

The main issue here is that SFSafariViewController is [not an ordinary VC](https://stackoverflow.com/questions/62135577/safariviewcontrollerdidfinish-does-not-fire-when-swiping-down-to-dismiss) and does not have `isModalInPresentation` mode.

The only way to detect drag down is via SFSafariViewController's presenter `delegate`.
Presenter could be a DropIn OR (in case of Components) your app's UIViewController so assigning a `delegate` might break / override something on your end. 

As I suggested in my previous comment - the rule of thumb we use is to `stopLoading()` right after **payments/details** returns an Action. I agree that it provides a certain level of inconsistency.

As en alternative you can set `RedirectComponentStyle.modalPresentationStyle = .fullScreen` - there would be no dragging.

I will think about a way to delegate this somehow..
If you have any ides, feel free to share 😁

**Comment by descorp** [comment] 2020-11-24 14:41
3.8.0 is released!

I am going to close this ticket for now.
Feel free to respond in this thread or provide any additional feedback!

**Closed by descorp** 2020-11-24 14:41 UTC
Labels: waiting release
