### ISSUE TITLE
[ISSUE] - Safari can not open as the address is invalid

### ISSUE THREAD

**Issue by basheer411** [Adyen/adyen-ios#167] opened 2020-05-21 19:10 UTC
**Description**: 
I am trying to Implement iDeal Component Integration. can load `action` object with `RedirectComponent`.  encountered an issue with return Url 

**Issue** : 
 The next steps encountered an issue as "Safari can not open as the address is invalid" (PFA) - which I suspect its URI schema issue. As we are not supporting URI Schema's in my app, any alternative ways other than URI Schema? 

<img width="366" alt="Screenshot 2020-05-22 at 12 36 49 AM" src="https://user-images.githubusercontent.com/10904991/82596082-5b8bb800-9bc4-11ea-8a80-7acd348a6660.png">

**Comment by joostvandijk** [comment] 2020-05-22 07:11
Hi @basheer411,

What is the `returnUrl` you are currently passing in your request to `/payments`?

Best,

Joost

**Comment by basheer411** [comment] 2020-05-22 08:22
Hi @joostvandijk , 
I am sending The `returnUrl` as "myapp://APPBUNDLEIDENTIFIER" and the payload will be 
`{"issuer":"1121","returnURL":"myapp:\/\/com.jd.jdsports","type":"IDEAL"}`

Basheer

**Comment by joostvandijk** [comment] 2020-05-22 08:30
I see, and is there any reason why you can not register a URI scheme as described [here](https://developer.apple.com/documentation/uikit/inter-process_communication/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app)?

**Comment by basheer411** [comment] 2020-05-22 08:57
Yes, there is a  reason can we have any alternates to get them worked without URI?

**Comment by joostvandijk** [comment] 2020-05-22 09:46
Hi Bas, there is no other way to reliably intercept a message from Safari View Controller.

**Comment by descorp** [comment] 2020-06-16 10:44
hi @basheer411 

There is no technical limitation on using Universal links from the SDK side. The main concern with universal links is that if the user clicks the top right corner to return in safari, the next time the app won't be opened. Universal links is a perfect tool for features paired on mobile and web, but - as @joostvandijk mentioned above - it is not a reliably redirect technique.

I am going to close this ticket for now. If you have any questions or ideas, feel free to continue in this thread.

**Comment by basheer411** [comment] 2020-08-07 12:41
Hi @descorp 

when I am sending a universal link (`retrurnUrl` ) from `/payments`.  it's not opening the app. 
The same URL when I am accessing from outside of the app it's working as expected. 

is this the limitation from Adyen side? 

In general, Pasting a Universal Link directly into the Safari URL field doesn’t cause the app to open automatically. If you do this, you will have to manually pull the website down so that a prompt will appear at the top asking you to open the respective app. 


I think the Adyen redirect component is doing the same as above, as its hitting the SafariVC

**Comment by descorp** [comment] 2020-08-07 14:31
Hi @basheer411 

How do you call a RedirectComponent?
To trigger Universal App URL redirect you need to call `redirectComponentInstance.handle(_ action: RedirectAction)`.

**Comment by basheer411** [comment] 2020-08-07 14:54
Hi @descorp , 

Here is my code : 

 ```
private func presentRedirectComponent(with action: RedirectAction) {
        let component = RedirectComponent(style: redirectComponentStyle)
        component.delegate = self
        component.presentingViewController = UIApplication.topViewController()
        redirectComponent = component
        component.handle(action)
    }
```
I am not using `RedirectComponent.applicationDidOpen(from: url)`

**Comment by basheer411** [comment] 2020-08-07 17:05
Hi @descorp ,

will you please explain when `RedirectComponent`  invokes/calls/hits the `didProvide` method from the `ActionComponentDelegate`. to get the contents of `data.details` to pass this to your server. 

I can see `didFail` is hitting on `cancel` action of the attached screenshot. 

I assume on `continue` action I am switching to the browser and redirecting back to the app. still, it's not hitting `didProvide`

![IMG_10AB0B3EBE40-1](https://user-images.githubusercontent.com/10904991/89669505-2e19f500-d8fd-11ea-8d6f-92cb537073f4.jpeg)

**Comment by descorp** [comment] 2020-08-10 10:39
Hi @basheer411 

Here is the process [described in docs](https://docs.adyen.com/checkout/ios/components#step-4-additional-client-app):

1. Make a `/payment` request. Make sure that "returnURL" is your custom URL scheme or Universal App Link URL
2. Checkout API generates RedirectAction with some 3rd-party app / website
3. SDK opens 3rd-party app or website
4. Shopper finishes payment flow on web/app; 3rd party call "returnURL" with payment details as query.
5. In AppDelegate handles Custom URL Scheme or Universal App Link and call `RedirectComponent.applicationDidOpen(from: url)`
6. SDK will gather all info from url's query and return `delegate.didProvide(...)`

**Comment by basheer411** [comment] 2020-08-12 20:07
Hi @descorp , 

I think the issue is at point number 5 on the above comment. 
you are right, that SDK is appending all info (payload, status, type) to the URL(Univeral Link), but it's not firing `delegate.didProvide(...)`

I think its because of the session expired after `redirect` from the app

is there any issue If I will manage the URL by extracting with URL components fetch ActionComponentData (payload, status, type etc..) in my custom class/method instead of waiting for `delegate.didProvide(...)` to fire and proceed for /details call?

In both ways, the result will remain the same.

**Comment by descorp** [comment] 2020-08-13 13:44
Do you persist RedirectComponent up until the payment is confirmed?

> is there any issue 

Sure. The network call have to be managed on app level any way.
If you need an example - this is how [AdditionalDetails is gathered from url](https://github.com/Adyen/adyen-ios/blob/master/Adyen/Components/Redirect/RedirectDetails.swift)

But I would recommend to figure out what is happening with `delegate.didProvide(...)` first..

**Comment by basheer411** [comment] 2020-08-14 17:52
Thanks for confirming no issues with doing manually.

> But I would recommend to figure out what is happening with delegate.didProvide(...) first..

I think the while app switching, RedirectComponent session has existed. but when redirecting back to the app 
RedirectComponent doesn't exist. The appDelegate hits `restorationHandler` and we handling the link (navigate to ideal payment VC which was initiated earlier) by this time RedirectComponent will not exist so that the delegates will not respond and leading `/details` to call manually.
`

**Comment by descorp** [comment] 2020-08-17 13:45
Hi @basheer411 

There is no session in RedirectComponent.
The idea to persist RedirectComponent is to store a delegate to ActionComponentDelegate - the one that will return `didProvide(...)` when Universal Link processed. 
In other words, to get delegate.didProvide(...) firing you have to keep the RedirectComponent instance.

**Comment by descorp** [comment] 2020-08-24 09:50
Hi @basheer411 

Yes, the link looks good to me. The query parameters are added by the payment method. 
The `resultCode` is reliable here, but I would advise always checking the Adyen API response: some other redirect-based payment methods might not have this query parameter.

**Comment by descorp** [comment] 2020-09-21 09:15
Hi @basheer411 

Were you able to successfully perform a Universal Link redirect?

**Comment by basheer411** [comment] 2020-09-21 09:31
Hi @descorp , 
I have tested in UAT, they are working as expected, we are not relay on `delegate.didProvide(...)` 
we just capturing **`paymentData`** from the universal link and sending to `/details`. 

The purpose of Universal link to redirect back to the app when user paying through Banking App. 
 I have a question around, .i.e. what is the behaviour of completing the payment without banking app?
will it call Universal link?  as we are sending this to the **/payments**

**Comment by descorp** [comment] 2020-09-21 13:44
Hi @basheer411 

Glad that you were able to make Universal link work, well done!

> completing the payment without banking app?

You mean via the Bank's web site when shoppers have no app installed?

All redirect-based payments (Paypal, iDEAL, WeChat, CardComponent with web 3DS e.t.c) are expected to call a "returnURL" after completion. There is no difference whether it was done by SFSafariViewController or 3rd party app.

**Comment by descorp** [comment] 2020-10-26 11:24
Hi @basheer411 

I am going to close this ticket for now, since we confirmed Universal Links to work as expected.
If you have any questions or ideas, feel free to continue in this thread.

**Closed by descorp** 2020-10-26 11:24 UTC

**Comment by fidoafif** [comment] 2021-04-22 01:48
> Hi @descorp ,
> 
> I think the issue is at point number 5 on the above comment.
> you are right, that SDK is appending all info (payload, status, type) to the URL(Univeral Link), but it's not firing `delegate.didProvide(...)`
> 
> I think its because of the session expired after `redirect` from the app
> 
> is there any issue If I will manage the URL by extracting with URL components fetch ActionComponentData (payload, status, type etc..) in my `custom class/method` instead of waiting for `delegate.didProvide(...)` to fire and proceed for` /details` call?
> 
> In both ways, the result will remain the same.

Hi it seem `delegate.didProvide(...)` not firing after authorized payment and get type = complete,

**Comment by fidoafif** [comment] 2021-04-22 01:52
https://user-images.githubusercontent.com/9498128/115643765-ff8b5f80-a34f-11eb-9eaf-170604e79372.mov

My case is stuck on inApp safari browser, the return url that I used is deep link `my-app://`, and the deep link is working on safari app

**Comment by descorp** [comment] 2021-04-22 07:59
Hi @fidoafif 

Thanks for reaching out!

> return url that I used is deep link my-app://, and the deep link is working on safari app

You mean if you call `my-app://` URL on Safari - system asks if you want to open your app? 

Just to clarify:
You have flowed all steps on [how to handle the redirect result](https://docs.adyen.com/payment-methods/molpay/ios-drop-in#handle-the-redirect):
- registered custom url-scheme in your Info.plist 
- passed the url-scheme in `"returnUrl" : "my-app://",` 
- call `RedirectComponent.applicationDidOpen(from: url)` on AppDelegate for inbound urls.

```swift
func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool {
        RedirectComponent.applicationDidOpen(from: url)
        return true
    }
```

From what I see on the video above - either the redirect didn't happen at all (something is wrong with `returnURL`) or it was not handled(the `RedirectComponent.applicationDidOpen(from: url)` not called).
Redirect supposed to happen when you see "Your payment is authorised" page.
