### ISSUE TITLE
How to test Swish in iOS application

### ISSUE THREAD

**Issue by MinaAshna** [Adyen/adyen-ios#1760] opened 2024-07-30 08:47 UTC
I have followed the [Swish Drop-in integration](https://docs.adyen.com/payment-methods/swish/ios-drop-in/) guide and added Swish as a payment method in test customer area and implemented the Drop In. I can successfully see Swish in the Drop In list and I can select it and open the Swish app on a mobile device. I have also implemented `onOpenURL` in my SwiftUI app to receive redirects.
`.onOpenURL { url in
                RedirectComponent.applicationDidOpen(from: url)
 }`
 I am aware of [Merchant Swish Simulator](https://developer.swish.nu/api/mss/v1) and yet not sure how to use it.
I'd appreciate if you could give some instructions on how to test Swish and get a redirect in my app.

**Comment by descorp** [comment] 2024-07-30 09:33
Hey @MinaAshna 

The easiest and most reliable thing is to perform a penny test on a real Swish bank account on LIVE.

---

If you looking to perform a full end-to-end TEST run, you can find more details on how to obtain [Swish Test application](https://developer.swish.nu/documentation/environments#user-enrolment) on Swish Development documentation.

**Comment by MinaAshna** [comment] 2024-07-30 09:51
Thanks for the reply. Not living in Sweden makes it difficult to do a penny test. I'll look into the Test Application.

**Comment by MinaAshna** [comment] 2024-08-12 10:49
Hi, @descorp,
I have reach out to Swish regarding test app, and I have set up Swish Sandbox app and Bank ID. 
The Drop In successfully prompt to open the Swish Sandbox
![app open](https://github.com/user-attachments/assets/ba87338b-1022-4424-89a9-e45cb41246a8)
But the Swish app fails with no obvious reason.
![error](https://github.com/user-attachments/assets/9193ef78-5855-4455-8bae-a2beae042bba)
At this point, I can see in the Adyen test dashboard, that the payment has gone through and it's settled, but I receive no redirect in the app to update the UI.
Do I need to set up a call back URL in Xcode? I would usually set up something like this: `swish://paymentrequest?token=<token>&callbackurl=<callbackURL>` but now since I'm not triggering the app switch to Swish, how should the URL Type look in Xcode?
Any idea why this is happening?

**Comment by descorp** [comment] 2024-08-12 12:01
Hi @MinaAshna 

> The Drop In successfully prompt to open the Swish Sandbox

This is usually enough 🤔

> Swish app fails with no obvious reason

Potential reasons 
- URL is wrong (character lost due to escaping etc)
- misconfiguration on your [CA](https://ca-test.adyen.com/ca/ca/) 
- Swish app internal issue. 

Do you have access to the URL?

**Comment by MinaAshna** [comment] 2024-08-12 13:33
I do have access to the Dashboard and I can see Swish is added as a Payment Method next to Card and Apple Pay. (Settings -> Payment Methods). But I can't make any configurations to Swish, if that's the case.

I have also run this by Swish Customer Service too. They were wondering if Adyen is sending the payment requests towards their "Sandbox Staging" or "MMS".
Could this possibly be the reason?

**Comment by descorp** [comment] 2024-08-12 13:57
> Could this possibly be the reason?

In theory - sure. 
We will run some tests locally tomorrow and let you know

**Comment by descorp** [comment] 2024-08-13 12:53
Hey @MinaAshna 

Sorry, I was unable to activate the Swish TEST environment today.
Will keep you posted.

**Comment by descorp** [comment] 2024-08-15 15:03
Hey @MinaAshna 

The behaviour you see is caused by an acquirer account set for Swish on your TEST CA. 
You probably have a default one (`Swish_Adyen`) that is not mobile friendly.

You can reach our Support Team via [Customer Area](https://ca-test.adyen.com/ca/ca/contactUs/support.shtml) or via email: [support@adyen.com](mailto:support@adyen.com) and ask them to change your Swish acquirer account to
`Swish_Sandbox_Adyen` - it have a full Swish Sandbox mobile flow support.

**Comment by MinaAshna** [comment] 2024-08-16 07:08
Thanks, for the update. In the meanwhile, I managed to do also do a penny test with the Swish app in production as you recommended. That failed with the same error and no call back to the app. Would it still be related to the configuration in TEST CA?

**Comment by descorp** [comment] 2024-08-16 08:03
> I managed to do also do a penny test with the Swish app in production

Just to clarify, you used real Swish app with a real Swish account on TEST environment?

**Comment by MinaAshna** [comment] 2024-08-16 08:29
Correct. Real Swish app with a real Swish account on Adyen TEST environment. I don't expect this to work, but you mentioned earlier that I can do a penny test, did you mean, penny test on Adyen Live?

**Comment by descorp** [comment] 2024-08-16 11:37
> real Swish account on Adyen TEST

This is probably the issue - TEST and LIVE have different encryption keys, so one can't use URL generated for TEST on LIVE app and visa versa.
To provide proper penny test, one needs real Swish account on Adyen LIVE

**Comment by MinaAshna** [comment] 2024-08-16 12:50
Thanks for the support. I'll contact Adyen support for the update on the acquire account.

**Comment by descorp** [comment] 2024-08-29 13:57
Hey @MinaAshna 

Any luck?

**Comment by MinaAshna** [comment] 2024-08-29 14:02
Hi,
After contacting both Swish and Adyen customer service, they all agreed that it is not possible to test Swish on test environment due to a technical issue with the acquirer account. The only way to move forward is to test with both Swish and Adyen in live environment, which is unfortunate. We are preparing for live environment, but that will take a while.

**Comment by descorp** [comment] 2024-08-29 14:18
Sorry to hear that. Swish is a tricky payment method to setup.

Here are two reassuring points:
1. If the redirect from your app to the Swish app happens successfully, the flow is "technically" working. 
2. If it were not working on LIVE, we would have known by now 😅
 
I will close this ticket as it falls slightly beyond the scope of Adyen iOS SDK. However, please feel free to share your findings here!

**Closed as completed by descorp** 2024-08-29 14:18 UTC
