### ISSUE TITLE
ButtonStyle borderWidth not behaving as expected with cornerRadius[BUG] 

### ISSUE THREAD

**Issue by isidoro-giffgaff** [Adyen/adyen-ios#593] opened 2021-08-11 14:47 UTC
**Describe the bug**
There's seems to be an issue with the introduction of borderWidth in the ButtonStyle. When used together with cornerRadius the behaviour is different than expected. Please see screenshot below.

**To Reproduce**
Steps to reproduce the behaviuor:
1. Create a new CardComponent and use the following mainButton style

```
var buttonStyle = ButtonStyle(title: .init(font: .systemFont(ofSize: 14), color: .black), cornerRadius: 20, background: UIColor(red: 0.99, green: 0.76, blue: 0.12, alpha: 1.00))
    
buttonStyle.borderColor = .black
buttonStyle.borderWidth = 3

```
**Expected behavior**
Corner radius shouldn't cut the border of the component.

**Screenshots**
![Simulator Screen Shot - iPhone 11 Pro - 2021-08-11 at 14 44 22](https://user-images.githubusercontent.com/62879426/129049965-049afe53-a7ca-4842-a019-c5dc4a589074.png)
**Smartphone (please complete the following information):**
 - Device: iPhone 12 
 - OS: iOS 14.5
 - SDK Version 4.0.0

**Comment by descorp** [comment] 2021-08-11 16:14
Hey @isidoro-giffgaff 

Indeed, good catch!
We are cutting the corner by applying a custom mask, so standard border is not working.
I'll create a ticket - hopefully we can make a fix before 4.1.0 release.

For now, unfortunately, there is no quick fix.
I can only suggest to use one of two: corner radius OR border. 

Thanks for a feedback and sorry for the inconvenience.

**Comment by descorp** [comment] 2021-08-12 09:41
Fixed on develop.
The fix will be released with 4.1.0

**Comment by sasindroid** [comment] 2021-08-25 14:56
Hi @descorp whats the schedule for 4.1.0?

**Comment by descorp** [comment] 2021-09-07 13:54
Hey @sasindroid 

Can you check on v4.1.0 ?

I can't reproduce it locally:

```swift
var style = FormComponentStyle()
style.mainButtonItem.button.backgroundColor = .systemYellow
style.mainButtonItem.button.borderColor = .black
style.mainButtonItem.button.cornerRounding = .fixed(20)
style.mainButtonItem.button.borderWidth = 5
style.mainButtonItem.button.title.color = .black
```

![Screenshot 2021-09-07 at 15 40 48](https://user-images.githubusercontent.com/2648655/132355035-79796135-45b8-473e-89d9-4f36d5ca6c95.png)

**Comment by descorp** [comment] 2021-09-21 14:41
I am going to close this ticket for now.
Please feel free to reopen if necessary.

**Closed by descorp** 2021-09-21 14:41 UTC
Labels: bug, awaiting feedback
