### ISSUE TITLE
Redirect component returns details (from some banking apps) that can not be encoded?

### ISSUE THREAD

**Issue by leslieolivier** [Adyen/adyen-ios#799] opened 2022-02-17 13:47 UTC
We are using iDEAL with direct issuer links enabled and iOS SDK 4.4.0.

For a subset of iDEAL payments (ansbank.nl and snsbank.nl - our return_url is probably called from the respective banking apps), the `didProvide` method returns some `ActionComponentData`, that seems to be unable to be encoded with this:

  `if let detailsPayloadData = try? JSONEncoder().encode(data.details.encodable), 
                 let detailsPayloadString = String(data: detailsPayloadData, encoding: .utf8) { ... }`

Unfortunately we currently don't have a way of seeing what the banking apps are sending to our app. When this encoding fails, we currently sent `{returnUrlQueryString=dummy=dummy}` to the Adyen backend, because when using v66 of backend API, we could not send an empty `returnUrlQueryString`. However this fails on v68 of the API with "Invalid payment method details".

Do you have any insight into what these banking apps could be returning and why the JSON encoding (or UTF-8 encoding) would fail? Most other iDEAL payments return "pspEchoData=2132132.....etc" as query parameters.

And what would the correct way to proceed be, if we do not have any details to send back to our backend? For the banks mentioned, we do actually get a Adyen notification asynchronously a couple of minutes later, so the user did succeed authorising the payment, but the return_url somehow does not contain something we can use to synchronously call the `/payments/details `endpoint on the backend.

Thanks!

**Comment by descorp** [comment] 2022-02-17 15:39
Hey @leslieolivier 

It is very possible that some specific PSP acts unexpectedly (or has started doing so recently).
Ideally, we would like to know exact  returnURL query.
Could you share a `pspreference` of such transaction or anyhow determine which iDeal bank it is?

In our [code](https://github.com/Adyen/adyen-ios/blob/develop/AdyenActions/Components/Redirect/RedirectDetails.swift#L54-L68) we expect anything, but en empty query. If this is the cause of the issue - something is malfunctioning on PSP side.

**Comment by leslieolivier** [comment] 2022-02-17 17:12
Hi @descorp!

I only have pspReferences from the when the Adyen notification comes in. An example is 4636450331172181 which is from SNS bank in NL (cardtype idealsns, ideal issuer: 0751). Another is 4656450233043162 (ANS Bank - cardtype idealasn - ideal isser 0761).

When we used indirect issuer links (i.e. with the glue page), then we got authorised a lot quicker (average 36s) for these banks, but now we wait average 2.5 mins.

**Comment by descorp** [comment] 2022-02-17 17:48
Hey @leslieolivier 

> When we used indirect issuer links (i.e. with the glue page), then we got authorised a lot quicker (average 36s) for these banks, but now we wait average 2.5 mins.

This is the main purpose of `glue page` and it works really smooth on Web and Android. Unfortunately, iOS is not as seamless when it comes to http-redirect.

> I only have pspReferences from the when the Adyen notification comes in. 

I guess this meant that we can look in other directions then SNS and ANS 😄
Thanks for feedback, we will conduct internal investigation as well..

BTW, can you assume how frequent does it happen?

**Comment by leslieolivier** [comment] 2022-02-17 18:07
Hi again,

> I guess this meant that we can look in other directions then SNS and ANS 

The payments are going through to our system via the notifications, but before that we have already cancelled the order, so we need to refund the money. We cancel it when we can't encode the details from the RedirectComponent. This happens for ALL payments through ANS/SNS. All other iDEAL payments are working, it seems. 

> BTW, can you assume how frequent does it happen?

With ANS and SNS it happens 100% of the time, so we will disable direct issuer links for now, but would like to enable it again, when we have hopefully found the issue.

I would like to make a debug version, that could log the return_url + parameters from the banking app, but we do not have access to someone with the right bank to test it (unless we do it in production). Would you be able to find out what the query parameters contain (if anything) when using ANS or SNS through iDEAL with direct issuer links?

**Comment by mohammedDehairy** [comment] 2022-11-10 08:28
direct issuer links are indeed not the best way to go about optimizing ideal payments, we're experimenting with new ways to optimize the redirect flow for ideal and other payment methods, so will close this issue for now, please feel free to reopen or create a new issue if you're still experiencing issues!.

**Closed as completed by mohammedDehairy** 2022-11-10 08:28 UTC
