### ISSUE TITLE
[BUG] Dismiss dropInComponent on didSubmit or didProvide

### ISSUE THREAD

**Issue by badredaha** [Adyen/adyen-ios#181] opened 2020-06-16 16:59 UTC
**Describe the bug**
If i dismiss dropInComponent when didSubmit or didPorvide is called (as mentioned in the doc) 
and i have the challenge to handle the screen for the challenge screen appear and disappear speedily  ??? 

But when i don't dismiss the dropInComponent all works Good but the component remains dispalyed.

example for dismiss component :
`self.dropInComponent.viewController.dismiss(animated: true, completion: nil)`

**Comment by descorp** [comment] 2020-06-17 09:39
Hi @badredaha 

no need to dismiss dropInComponent on didSubmit or didProvide.
Dismission should occur only on 'didFail'.

Could you point me to a documentation you are mentioning? I'll check the integrity.
In a meanwhile I would recommend to use [out HostUI app](https://github.com/Adyen/adyen-ios/blob/master/AdyenUIHost/Domains/Components/ComponentsViewController.swift#L236) as a reference.


Another thing:

DropIn component is a UINavigationContrtoller under the hood. Depending on a current state, it could present other view controllers. 
To dismiss a `dropInComponent` better use a `dismiss` on parent view controller on your App level.

Check [Apple documentation](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621505-dismiss): 
> The presenting view controller is responsible for dismissing the view controller it presented. 

>If you present several view controllers in succession [...] calling this method on a view controller lower in the stack dismisses its immediate child view controller and all view controllers above that child on the stack.

**Comment by badredaha** [comment] 2020-06-17 10:33
Hi,

Thx for your answer.

In the doc they mentioned that you can dismiss dropincomponent (in bold)

### Drop In iOS

> 

threeDS2Fingerprint | The payment qualifies for 3D Secure 2, and will go through either the frictionless or the challenge flow.Drop-in performs the authentication flow, and calls the didProvide method. | 1. Get thedata.details from the didProvide method and pass it your server. **Dismiss the dropInComponent immediately**, or wait until you have submitted the details to your server.2. Proceed to step 5 to submit additional payment details.
-- | -- | --
threeDS2Challenge | The payment qualifies for 3D Secure 2, and the issuer is initiating a challenge flow.Drop-in performs the authentication flow, and calls the didProvide method. | 1. Get the data.details from the didProvide method and pass it your server. **Dismiss the dropInComponent immediately**, or wait until you have submitted the details to your server.2. Proceed to step 5 to submit additional payment details.
**SDK**The type can sometimes include the payment method name. For example, wechatpaySDK. | Drop-in triggers the app switch from your app to the payment method's app, if installed in the shopper's device.When the shopper is redirected back to your app, Drop-in calls the didProvide method. | 1. Get the data.details from the didProvide method and pass it your server. Dismiss the dropInComponent immediately, or wait until you have submitted the details to your server.2. Proceed to step 5 to check the payment result.

**Comment by descorp** [comment] 2020-06-18 09:15
Hi @badredaha 

Sorry for misleading you. See my updated comment above.
Documentation is not really descriptive, but for sure says nothing unjust :D

**Comment by badredaha** [comment] 2020-06-18 21:28
:D thx @descorp 

My concern is if the user begins payment process and click cancel ! what should i do ? send another request to cancel the payment ? if so how i can be sure ? 

This is why i asking. My optimal use case is when the use begins the process i dismiss the dropincoponent and i show the loading page and if any challenges the handle.action handle this and continue normally.

**Comment by descorp** [comment] 2020-06-19 09:36
Hey @badredaha 

That is a valid question!
After some consideration, we are going to disable "cancel" while the payment is in progress on 3.6.0.

In other words, there are only two way to dismiss  DropIn:
- User clicking "cancel" before any **payment** started;
- You app deliberately dismisses DropIn.

**Comment by badredaha** [comment] 2020-06-19 09:51
Hey @descorp 

Thx a lot :)

**Comment by badredaha** [comment] 2020-06-19 10:31
Hey,
For example If we have a challenge  (Printfinger for exemple) and we Dismiss the component into  just into didProvide (and as we know didProvide take a lot time :/) and after the  "Purchae Authentification" is appear  AND ALL WORK NICE.

But if we put the dismiss into didSubmit the "Purchae Authentification"  Appear and Disappear immediately. 

i hope understand my use case and examples 👯

**Comment by descorp** [comment] 2020-06-19 11:05
> But if we put the dismiss into didSubmit the "Purchae Authentification" Appear and Disappear immediately.

This could be due to the bug on DropInActionComponent. In 3.5.0 DropInActionComponent rely on a dropInPomponet.viewController to present 3DS challenge or redirects.
When you dismiss DropIn you also dismiss 3DS challenge :D 

To work it around:

1. Do not use `dropInComponent.handle(action)`. Instead, use local instance of DropinActionComponent.
2. Do network request **after** dropIn is dismissed. For e.x. wrap it in completion block of `dismiss` function.

```swift
    func didSubmit(_ data: PaymentComponentData, from component: PaymentComponent) {
        self.dismiss(animated: true) {
            performPayment(with: data)
        }
    } 
```

**Comment by badredaha** [comment] 2020-06-19 11:27
can i have example for DropinActionComponent integration ?

**Comment by descorp** [comment] 2020-06-19 14:31
Sure @badredaha 

```swift
    private lazy var actionComponent: DropInActionComponent = {
        let handler = DropInActionComponent()
        handler.presenterViewController = self
        handler.delegate = self
        return handler
    }()
```

When you send out `PaymentComponentData ` or `ActionComponentData ` to your backend, and in response, you receive an `Action ` use: 

```swift
   actionComponent.perform(action)
```

You can find whole implementation in [HostUIApp](https://github.com/Adyen/adyen-ios/blob/master/AdyenUIHost/Domains/Components/ComponentsViewController.swift)

**Comment by badredaha** [comment] 2020-06-19 18:58
Doesn't work :/ into didSubmit even with this solution ! the "Authentication Screen Challenge" Appear and Disappear immediately.

Its work just into didProvide (like i make it first time and the problem still the same didProvide take a lot time and the user can click to cancel button)

**Comment by descorp** [comment] 2020-06-22 16:44
Hi @badredaha 

Could you share a GIF / Video?
How, when and how many times are you calling `dismiss()`?
Do you see any error messages when 3DS dismissed?
Is your `dropInComponent` persisted until the payment completed?

The only way I was able to reproduce described behaviour is by dismissing DropIn **right after** Action with `threeDS2Challenge` was handled by DropInActionComponent.

**Comment by descorp** [comment] 2020-06-25 09:58
Hi @badredaha 

3.6.0 is released. 'Cancel' is no longer enabled while payment in progress. 
Now you can avoid dismissing DropIn till payment is completed. 

Could you verify if this solves your issue?

**Comment by descorp** [comment] 2020-07-14 11:00
Hi @badredaha 
I am going to close this ticket for now. 

If you have anything, please feel free to follow app in this thread.

**Closed by descorp** 2020-07-14 11:00 UTC
