### ISSUE TITLE
[BUG] Apple Pay not shown in drop in component

### ISSUE THREAD

**Issue by alex-tiqets** [Adyen/adyen-ios#1021] opened 2022-10-14 11:05 UTC
Hi,

We just noticed that Apple Pay is not being shown as an option in our app and app clip's drop in component. The version in the App Store was released before iOS 16 and everything was tested and working properly. If we run the latest build of our app (not yet released), everything works in the simulator (for both debug and release builds), but not on device.

We do get Apple Pay in the response from the server.

Here's our config:
```swift
let configuration = DropInComponent.Configuration(apiContext: apiContext)
configuration.card.showsStorePaymentMethodField = true
configuration.card.showsHolderNameField = true
configuration.applePay = .init(
    summaryItems: [ .init(label: "\(payment.label)", amount: NSDecimalNumber(value: payment.amount), type: .final) ],
    merchantIdentifier: applePayMerchantIdentifier
)
configuration.payment = .init(from: payment)
dropInComponent = .init(paymentMethods: paymentMethods, configuration: configuration)
```

And here's the result:

![IMG_4616](https://user-images.githubusercontent.com/112863322/195829448-117f67c4-57ef-4bfe-89c7-37fdef21ca9a.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.0
 - SDK Version 4.9.0

**Additional context**

We just discovered that it may have to do with the type of card that was added to Apple Pay. When selecting a payment option, debit cards in the Netherlands (ABN AMRO, ING) are marked as unacceptable by the app.

Alex

**Comment by descorp** [comment] 2022-10-14 12:41
Hey @alex-tiqets 

Do you have Apple Pay MerchantID in your `.entitlements` file?
Is app correctly signed?

**Comment by alex-tiqets** [comment] 2022-10-14 12:54
Yeah, everything is configured properly - we've been using Adyen for awhile now. After a morning of debugging internally, we now think that it comes down to debit cards. One of the colleagues has a credit card, so the Apple Pay option is shown. If he taps on the option to choose cards, the debit cards are marked as unavailable:

![IMG_3082](https://user-images.githubusercontent.com/112863322/195850931-67279236-bf14-45d7-9cfd-99f9f7f77dee.png)

In other cases, if you only have a debit card in Apply Pay, the empty drop in component is shown as in the first screenshot.

It wasn't like this before and the debit cards used to work. We also tested it on our web site and the debit cards work.

**Comment by descorp** [comment] 2022-10-17 10:33
Hey @alex-tiqets 

> It wasn't like this before

What have changed? SDK version?

> the debit cards are marked as unavailable:

Both debit cards are `maestro`.
Is it available on your Adyen Portal as payment method? 
What do you see on `brands` field in `\paymentMethods` response for Apple Pay?

If not - check with your Adyen Account Manager or [contact support](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420)

**Comment by alex-tiqets** [comment] 2022-10-17 11:28
> What have changed? SDK version?

Might have been the update to iOS 16.

> Is it available on your Adyen Portal as payment method?

It is.

> What do you see on brands field in \paymentMethods response for Apple Pay?

```
      - name : "Apple Pay"
      ▿ brands : Optional<Array<String>>
        ▿ some : 4 elements
          - 0 : "amex"
          - 1 : "cartebancaire"
          - 2 : "mc"
          - 3 : "visa"
```

But it is exactly the same response that we get on the web. And Apple Pay works there.

**Comment by descorp** [comment] 2022-10-17 15:37
> But it is exactly the same response that we get on the web. And Apple Pay works there.

what SDK and API version are you using on web?
Could you provide PSP reference for a successful web transaction?

**Comment by descorp** [comment] 2022-10-17 15:44
BTW @alex-tiqets 

We do not recommend to use DropIn for a single Apple Pay payment.
Better use standalone `ApplePayComponent`

**Comment by alex-tiqets** [comment] 2022-10-18 07:40
> what SDK and API version are you using on web?

Web components 4.9.0 and Adyen API v67

> Could you provide PSP reference for a successful web transaction?

[NQ4J3FXKJP7NQPB2](https://ca-live.adyen.com/ca/ca/accounts/showTx.shtml?pspReference=NQ4J3FXKJP7NQPB2&txType=Payment)

> We do not recommend to use DropIn for a single Apple Pay payment.
> Better use standalone ApplePayComponent

Thanks, will look into it.

**Comment by descorp** [comment] 2022-10-18 15:12
Hey @alex-tiqets 

Interesting case!
Your account on CA does not have `maestro_applepay` configured, but the payment is handled ~~via the tool, called "Apple Pay mass enablement".~~ handled as co-branded Master Card.
This is ~~indeed an inconsistency from Adyen's side.~~ expected behaviour.

It is probably working on the web because they somehow override `brands` from `paymentMethods` 🤔
You can do one of two things:

1) add `maestro_applepay` to CA (ask [support](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420) if you need help with this)
2) manually generate ApplePayPaymentMethod with `brands` that contains all necessary networks or simply set it to `nil`

~~I'll report this inconsistency as a bug for the API team.~~
Thanks for your feedback! 💚

**Comment by alex-tiqets** [comment] 2022-10-19 06:01
That’s very helpful! Thank you Vladimir 🙌🏻

**Comment by descorp** [comment] 2022-10-20 15:22
Hey @alex-tiqets 

sorry, my original answer was incorrect - turned out it is not a bug, it is a feature 😅
I have edited it.

**Comment by mohammedDehairy** [comment] 2022-11-10 08:20
will close this issue for now, please feel free to reopen or create a new issue if you're still experiencing issues!.

**Closed as completed by mohammedDehairy** 2022-11-10 08:20 UTC
Labels: wontfix
