### ISSUE TITLE
Support for Swift Package Manager (SPM)

### ISSUE THREAD

**Issue by MattCheetham** [Adyen/adyen-ios#146] opened 2020-03-11 12:16 UTC
I'd really love support for Swift Package Manager in this SDK. Many popular frameworks now support Swift Package Manager as it makes it super simple for people to integrate your SDK by just pasting the GitHub URL of your project into Xcode.

You can read more about SPM here: 
https://developer.apple.com/documentation/swift_packages

**Comment by mohammedDehairy** [comment] 2020-03-12 12:28
Hi @MattCheetham ,

 This is a very good idea, we'll discuss internally, and probably will be supported soon.

Best regards

Mohamed

**Comment by piercifani** [comment] 2020-03-26 10:11
This is also something we'd be interested in

**Comment by mohammedDehairy** [comment] 2020-04-14 13:49
Hi @MattCheetham,

 We have investigated SPM, and found a blocking problem to support it, SPM doesn't support closed-source prebuilt binary artifacts as dependencies, which we do (Checkout SDK has Adyen3DS2 SDK as a dependency and its closed source prebuilt binary), fortunately there are proposals to add such support, so maybe with one the future releases of Xcode.

**Comment by MattCheetham** [comment] 2020-06-12 22:35
Thanks for investigating. Swift 5.3 supports compiled binary dependencies and should be available in the coming months. I’ll try and check back once that becomes available.

**Comment by kikettas** [comment] 2020-09-17 09:28
Any plans on adding SPM support now that Carthage is not working?

**Comment by mohammedDehairy** [comment] 2020-09-17 11:59
Hi @kikettas ,

 We're working on it, we have technical difficulties, since SPM doesn't seem to support packages that have mixed objective c and swift code, so we're going to try to rewrite the objective c code to swift, but it will take some time.

**Comment by piercifani** [comment] 2020-09-17 12:02
Hey @mohammedDehairy, that is not entirely accurate: if there are no cross referencing (from ObjC to Swift and vice-versa), then you can mix it in the same target, like [this](https://github.com/theleftbit/BSWInterfaceKit/tree/develop/Sources)

**Comment by kikettas** [comment] 2020-09-17 12:05
Hi @mohammedDehairy,

As @piercifani points out, you can mix it. You can find another example of this in the Facebook SDK [Package.swift](https://github.com/facebook/facebook-ios-sdk/blob/master/Package.swift) file 👍

**Comment by mohammedDehairy** [comment] 2020-09-17 12:06
Hey @piercifani  @kikettas ,

 The Swift code calls the Objective c code in the same target.

**Comment by piercifani** [comment] 2020-09-17 12:08
Then yeah, you can layer the code as the ObjC files in a separate target, and you call that from the Swift target. No need to rewrite your code.

**Comment by mohammedDehairy** [comment] 2020-09-17 12:10
Hey @piercifani ,

 We were planning to rewrite the objective c code any way to swift, but if this plan doesn't work out, then we will indeed move the Obj-c code to it own target. :-)

**Comment by mohammedDehairy** [comment] 2020-09-17 12:22
is this blocking for you? @piercifani @kikettas , didn't quite get your comment:

```
now that Carthage is not working?
```

what's the problem with Carthage? is it the issue related to Xcode 12?

**Comment by kikettas** [comment] 2020-09-17 15:00
Exactly, that issue doesn't seem to be addressed soon and Carthage has a tendency to be less and less maintained, so I guess we're not the only ones thinking on migrating to SPM.

**Comment by descorp** [comment] 2020-09-21 17:20
Hi @kikettas 

Indeed, the situation is unprecedented.
Unfortunately, Carthage community not making it on time with a stable fix :(
You can follow up on updates in #201 

The CocoaPods confirmed to work for Simulator with minor adjustments.
We will investigate about full stable compatibility.

SPM support will be addressed as a highest priority as well.

Sorry for the inconvenience.

**Comment by kikettas** [comment] 2020-09-22 09:33
Cool, glad to hear that SPM became a priority 👍.
For the time being, we have generated a fat library manually until you provide support for SPM.

**Comment by bukira** [comment] 2020-09-23 14:59
For the time being, we have generated a fat library manually until you provide support for SPM.

@kikettas how did you do that????

**Comment by kikettas** [comment] 2020-09-24 08:33
@bukira You need to compile the Adyen frameworks you need in your project for each architecture (arm7, arm64, x86 and i386) and create a fat library with all of those (one for each Adyen framework). Not difficult, but tedious and _boring_.

**Comment by bukira** [comment] 2020-09-24 08:38
Can you explain how? Do u mean make a XCFramework?

**Comment by kikettas** [comment] 2020-09-24 08:51
[This tutorial ](https://medium.com/@hassanahmedkhan/a-noobs-guide-to-creating-a-fat-library-for-ios-bafe8452b84b) might be useful for you. You can check the archs and library type by executing `file Adyen.framework/Adyen` in your terminal 👍

**Comment by kikettas** [comment] 2020-09-24 08:52
<img width="783" alt="image" src="https://user-images.githubusercontent.com/9082270/94123343-f850b180-fe53-11ea-8cd3-204cbaec8a78.png">

**Comment by bukira** [comment] 2020-09-24 09:37
Thanks your help, but im totally confused as to how this helps you work with SPM?

Thew problem I have is that with SPM you need to use an .xcframework if the product doesn’t support SPM, how does making a fat library help in anyway?

**Comment by kikettas** [comment] 2020-09-24 09:42
Oh, I'm not using SPM for Adyen as they don't support it. I'm just importing it manually into Xcode.

**Comment by bukira** [comment] 2020-09-24 09:44
But surely that’s what Carthage is for lol, or you dont use Carthage? Sorry I got me wires crossed, I thought you meant you could use SPM by making a fat library

**Comment by descorp** [comment] 2020-09-24 10:06
@bukira 

This is a confusion of highest order :D

In the current moment it is a bit painful to testing and developing on Xcode 12: 
- SPM is not yet supported y Adyen; 
- Carthage community is working hard to provide stable arm64 support;
- Cocoapods reported to have issues on iOS 14 (probably due to 3DS framework).

So as @kikettas confirmed - the fat library is the most reliable way to manage your dependencies at the moment.
We are working to improve the situation..

**Comment by bukira** [comment] 2020-09-24 10:08
if you allow “Build Libraries for Distribution” in the project settings thence make an xcframework,
Carthage works fine if you use the script the suggest, but to get Adyen to work in an SPM library you need to use an xcframework

**Comment by kikettas** [comment] 2020-11-16 14:11
Would it be available for the next release, am I guessing right?

**Comment by mohammedDehairy** [comment] 2020-11-16 14:20
@kikettas ,

Yes, it will be available next release.

**Comment by joeltrew** [comment] 2020-11-16 15:49
The current install instructions for SPM in the README seem to not work, putting the minimum version as 3.8.0 leads to an error saying no matched version, 3.70 doesn't work either as it says Package.swift found. 
I managed to get it to work by specifying the exact git hash `92f7b951de18deaa67d34faf24e6e9ee67292fdf`

**Comment by mohammedDehairy** [comment] 2020-11-16 17:43
@joeltrew ,

That makes sense, because we haven't released 3.8.0 yet, also 3.7.0 doesn't have Package.swift, that's why only the git hash works for now, until we release 3.8.0.

**Comment by bukira** [comment] 2020-11-23 09:57
when is 3.8.0 being released?

**Comment by descorp** [comment] 2020-11-23 10:07
@bukira Today hopefully 😄

**Comment by descorp** [comment] 2020-11-24 14:38
3.8.0 is released!
Waiting your feedback!

**Comment by kikettas** [comment] 2020-11-24 15:01
Awesome! Great job @descorp! We'll update soonish so we will forward you any issue if there´s any.

**Comment by bukira** [comment] 2020-11-25 08:45
I get this when adding to Package.swift

resource 'Localizable.strings' in target 'Adyen' is missing the default localization 'en-US'; the default localization is used as a fallback when no other localization matches

**Comment by mohammedDehairy** [comment] 2020-11-25 09:08
Hi @bukira ,

 Thanks for the feedback!.

 Unfortunately we couldn't get rid of this warning, the warning is complaining that the `Adyen` `Localizable.strings` is missing the `en-US`, but it is there, and we have tested the fallback whenever the device language is one which is not supported by the SDK, so localization and fallback to `en-US` works fine, but this warning is till persisting for some reason, but don't think its harmful in any way.

 Please let us know if localization and fallback to `en-US` is not working for you.

**Comment by bukira** [comment] 2020-11-25 09:13
All seems good,  had to do a bit of cleaning to get it to stop trying to use the old Adyen.framework, but working well, have to fix some UI as deprecated issues so the skins not looking right on the buttons and title

**Comment by bukira** [comment] 2020-11-25 09:32
In the new UI, I see that "Credit Card" is twice, on the title of the view with the "cancel" and also under it in the view itself
![IMG_0068](https://user-images.githubusercontent.com/226171/100208861-180e5f80-2f01-11eb-860c-86612142e7cf.PNG)

**Comment by mohammedDehairy** [comment] 2020-11-25 09:46
Hi @bukira ,

 You should set `showsLargeTitle` to false, its deprecated, but its default value was true before deprecation, so we didn't want to break merchant code that depend on it being default true.

**Comment by kikettas** [comment] 2020-11-30 10:14
Got an issue while deploying to iTunes Connect:
`"Invalid directory. The bundle Payload/MyApp.app/PlugIns/Adyen3DS2.framework is not contained in a correctly named directory. It should be under "Frameworks"."`

Any lead on this one? I could remove the framework from the `Plugins` in a build phase script, but maybe you have a better approach o there´s something you can do in your side.

**Comment by kikettas** [comment] 2020-11-30 10:14
It's pretty much described here https://forums.swift.org/t/swift-package-binary-framework-issue/41922/2

**Comment by bukira** [comment] 2020-11-30 10:15
This is most likely an Xcode 12 issue with SPM, had this with other SDKs and had to remove manually until apple fix the issue, happens on firebase SP

**Comment by mohammedDehairy** [comment] 2020-11-30 11:48
It indeed looks like an Xcode 12 issue.

We don't have a better approach, I would say follow the solution in the swift forum, and let us know if you need further assistance.

**Comment by kikettas** [comment] 2020-11-30 12:37
Alright 👍 Maybe it's good to have it documented somewhere so no one faces the same issue again!

**Comment by descorp** [comment] 2020-12-09 10:59
The documentation was added on [README](https://github.com/Adyen/adyen-ios#swift-package-manager)
Thanks everyone for feedback and support!

I am going to close it for now.
Feel free to provide any additional feedback in this thread or create a new one is necessary.

**Closed by descorp** 2020-12-09 10:59 UTC
Labels: awaiting feedback
