### ISSUE TITLE
Apple rejected app due to obfuscation

### ISSUE THREAD

**Issue by Sroka** [Adyen/adyen-ios#65] opened 2019-04-18 07:23 UTC
Hello,

Recently we got our app rejected due to code obfuscation after adding Adyen SDK. After unzipping .ipa and looking briefly into BCSymbolMap I found that, indeed, Adyen SDKs has some obfuscated symbols there. Did any of the other customers have any problems with this? It's a showstopper for us

We're using SDK version 2.7

**Comment by joostvandijk** [comment] 2019-04-18 07:31
Hi @Sroka,

This is due to the [3-D Secure SDK](https://github.com/adyen/adyen-3ds2-ios) embedded inside the SDK. The issue is being tracked [here](https://github.com/Adyen/adyen-3ds2-ios/issues/3). We have made temporary changes that prevent issues with the App Store submission process. They are included in version 2.7.3, but you might as well update to 2.8.0 as there are no breaking changes.

I'll close this issue, as we have one in the other repository. My apologies for the inconvenience.

With kind regards,

Joost

**Closed by joostvandijk** 2019-04-18 07:31 UTC

**Comment by jmarcinko-pcissc** [comment] 2019-10-30 16:35
@joostvandijk I'm trying to better understand the pervasiveness of this issue and the steps you took to address Apple's concerns. Was your approach simply to remove the obfuscated code/symbols or were you able to work with Apple to educate them on the intent behind the use of obfuscation?

**Comment by brurend** [comment] 2019-11-14 19:22
Is it possible that this is happening again? We just had a rejected because of obfuscation, but they didn't give enough details to confirm if it was at Adyen SDK or not. (We are updating the SDK to the newest version but are still using the version 2.8.*)

**Comment by joostvandijk** [comment] 2019-11-14 19:50
@brurend This shouldn’t happen. Normally, Apple gives a list of obfuscated symbols with these type of rejections. Did you receive that? Also, could you confirm which version of the Adyen3DS2 SDK you are using?

**Comment by brurend** [comment] 2019-11-18 17:52
@joostvandijk Apple confirmed to us that the problem is not related to any of Adyen SDKs.

**Comment by webkul-ramakant** [comment] 2020-03-25 13:58
Hi @joostvandijk I am facing the same issue and i am using the 3.3.0 version. Please help me.

**Comment by joostvandijk** [comment] 2020-03-25 14:02
@webkul-ramakant Did Apple provide a list of obfuscated symbols that caused the rejection?

**Comment by webkul-ramakant** [comment] 2020-03-25 14:09
@joostvandijk No, but Apple shows a message when we upload with Adyen SDK and stop to submit app in AppStore.
"Your app is using the Advertising Identifier (IDFA). You must either provide details about the IDFA usage or remove it from the app and submit your binary again."

**Comment by joostvandijk** [comment] 2020-03-25 15:24
@webkul-ramakant The Advertising Identifier is used in the 3DS2 SDK as per the EMVCo specification. It is used for risk analysis purposes in order to prevent fraud.
