### ISSUE TITLE
[BUG] ayden-ios fails to build via carthage on Xcode 12 betas 2, 3 , 4

### ISSUE THREAD

**Issue by intere** [Adyen/adyen-ios#201] opened 2020-07-30 15:54 UTC
**Describe the bug**
When trying to add ayden-ios as a dependency to a project using `Xcode 12 beta 3` via `Carthage`, the compilation fails with the following error:

```bash
⇒  carthage bootstrap --platform ios --use-ssh
*** No Cartfile.resolved found, updating dependencies
*** Fetching adyen-ios
*** Fetching adyen-3ds2-ios
*** Checking out adyen-3ds2-ios at "2.1.0-rc.5"
*** Checking out adyen-ios at "3.6.0"
*** xcodebuild output can be found in /var/folders/83/g4z5yhjj5cl5ww7gyf3h869m0000gp/T/carthage-xcodebuild.VDLNeQ.log
*** Downloading adyen-3ds2-ios.framework binary at "2.1.0-rc.5"
*** Building scheme "Adyen" in Adyen.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/einternicola/Code/watches/CarthageAydenExample/Carthage/Checkouts/adyen-ios/Adyen.xcodeproj -scheme Adyen -configuration Release -derivedDataPath /Users/einternicola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8169g/adyen-ios/3.6.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/83/g4z5yhjj5cl5ww7gyf3h869m0000gp/T/adyen-ios SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/einternicola/Code/watches/CarthageAydenExample/Carthage/Checkouts/adyen-ios)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/83/g4z5yhjj5cl5ww7gyf3h869m0000gp/T/carthage-xcodebuild.VDLNeQ.log
```

**To Reproduce**
1. Download and install Xcode12 beta 3
2. Use xcode select to set this as your xcode: `xcode-select --switch /Applications/Xcode-beta.app`
3. Create a new Xcode project
4. Create a Cartfile with the following contents: `github "Adyen/adyen-ios" == 3.6.0`
5. Execute the following command: `carthage bootstrap --platform ios --use-ssh`
6. Observe the failure (similar to what I noted above)

**Expected behavior**
I expect Carthage to build ayden-ios successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/2284832/88944648-3eb9d380-d24a-11ea-8608-2c5ee9b9c5c5.png)

**Smartphone (please complete the following information):**
 - Device: MacBook Pro (16-inch, 2019)
 - OS: macOS Catalina 10.15.5 (19F101)
- Xcode: 12.0 beta 3 (12A8169g)
 - SDK Version 3.6.0

**Additional context**
N/A

**Comment by descorp** [comment] 2020-07-30 15:59
Hi @intere 

Thanks for the feedback!
Could you also print out `xcodebuild` log?

**Comment by intere** [comment] 2020-07-30 16:03
Full log file:
[carthage-xcodebuild.VDLNeQ.log](https://github.com/Adyen/adyen-ios/files/5002419/carthage-xcodebuild.VDLNeQ.log)

**Comment by intere** [comment] 2020-08-03 16:06
In doing some more research, this might not be an Ayden specific issue: https://github.com/Carthage/Carthage/issues/3019

**Comment by descorp** [comment] 2020-08-03 16:16
Thanks a lot @intere !

Interesting.. I [wasn't able](https://github.com/Adyen/adyen-ios/runs/939998083?check_suite_focus=true) to reproduce it on Xcode 12.0 (12A8169g) that comes along with GitHub Actions.

Luckily, like there is a workaround
> Found a work around to allow use with Xcode 12 beta 3. You need to build your Carthage with Xcode 12 beta 2 and then you can run it with Xcode 12 beta 3. No changing project settings or build settings. This worked for iOS and tvOS targets

Could you verify if it works for you?

**Comment by intere** [comment] 2020-08-03 16:18
> Thanks a lot @intere !
> 
> Interesting.. I [wasn't able](https://github.com/Adyen/adyen-ios/runs/939998083?check_suite_focus=true) to reproduce it on Xcode 12.0 (12A8169g) that comes along with GitHub Actions.
> 
> Luckily, like there is a workaround
> 
> > Found a work around to allow use with Xcode 12 beta 3. You need to build your Carthage with Xcode 12 beta 2 and then you can run it with Xcode 12 beta 3. No changing project settings or build settings. This worked for iOS and tvOS targets
> 
> Could you verify if it works for you?

Yes, definitely.  I'm downloading beta 2 now.

**Comment by intere** [comment] 2020-08-03 16:46
I get the same error with Xcode 12 beta 2:
```
Undefined symbols for architecture armv7:
  "type metadata for Swift._StringObject.Variant", referenced from:
      outlined init with take of Swift._StringObject.Variant in IssuerListComponent.o
ld: symbol(s) not found for architecture armv7
```

See the attached log file:

[carthage-xcodebuild.NqG6pg.log](https://github.com/Adyen/adyen-ios/files/5017168/carthage-xcodebuild.NqG6pg.log)

**Comment by intere** [comment] 2020-08-03 21:25
This might also be of some help: https://developer.apple.com/forums/thread/649918

**Comment by descorp** [comment] 2020-08-04 09:30
Not all heroes wears capes! 🦸‍♂️
Thanks a lot @intere 

From what I can see - this is a temporary (I hope so) issue, that should be fixed with stable\next Xcode build.
Issue caused by using armv7 functionality on new arm64 architectures (looks like the `String` is a man suspect)

It could be fixed in two ways: 

1) by striping up armv7 architecture or rebuilding .framework with target version iOS13. [source1](https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323) [source2](https://developer.apple.com/forums/thread/649918?answerId=615750022#615750022) [source3](https://developer.apple.com/forums/thread/649918?answerId=624371022#624371022)
2) by dirty magic with Strings [source1](https://github.com/airbnb/lottie-ios/pull/1215/files) [source2](https://developer.apple.com/forums/thread/649918?answerId=614633022#614633022)

Unfortunately, we can't promise to fix it on our end quick enough( not before it is done by Cartages, at least :D )
I'll keep my eye on Cartage.

**Comment by intere** [comment] 2020-08-04 15:32
@descorp thanks for looking into it.  I'm hopeful that beta 4 drops soon with a fix.  🤞

**Comment by intere** [comment] 2020-08-04 21:40
Update - different error on Xcode 12 beta 4:
```
Ld /Users/einternicola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/adyen-ios/3.6.0/Build/Intermediates.noindex/Adyen.build/Release-iphonesimulator/AdyenCard.build/Objects-normal/arm64/Binary/AdyenCard normal arm64 (in target 'AdyenCard' from project 'Adyen')
    cd /Users/einternicola/Code/watches/CarthageAydenExample/Carthage/Checkouts/adyen-ios
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios10.0-simulator -dynamiclib -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk -L/Users/einternicola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/adyen-ios/3.6.0/Build/Products/Release-iphonesimulator -F/Users/einternicola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/adyen-ios/3.6.0/Build/Products/Release-iphonesimulator -FCarthage/Build/iOS -filelist /Users/einternicola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/adyen-ios/3.6.0/Build/Intermediates.noindex/Adyen.build/Release-iphonesimulator/AdyenCard.build/Objects-normal/arm64/AdyenCard.LinkFileList -install_name @rpath/AdyenCard.framework/AdyenCard -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/einternicola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/adyen-ios/3.6.0/Build/Intermediates.noindex/Adyen.build/Release-iphonesimulator/AdyenCard.build/Objects-normal/arm64/AdyenCard_lto.o -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/einternicola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/adyen-ios/3.6.0/Build/Intermediates.noindex/Adyen.build/Release-iphonesimulator/AdyenCard.build/Objects-normal/arm64/AdyenCard.swiftmodule -framework Adyen3DS2 -framework Adyen -compatibility_version 1 -current_version 3.6.0 -Xlinker -dependency_info -Xlinker /Users/einternicola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/adyen-ios/3.6.0/Build/Intermediates.noindex/Adyen.build/Release-iphonesimulator/AdyenCard.build/Objects-normal/arm64/AdyenCard_dependency_info.dat -o /Users/einternicola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/adyen-ios/3.6.0/Build/Intermediates.noindex/Adyen.build/Release-iphonesimulator/AdyenCard.build/Objects-normal/arm64/Binary/AdyenCard
ld: building for iOS Simulator, but linking in dylib built for iOS, file 'Carthage/Build/iOS/Adyen3DS2.framework/Adyen3DS2' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

See attached log file:
[carthage-xcodebuild.VpZWEA.log](https://github.com/Adyen/adyen-ios/files/5024769/carthage-xcodebuild.VpZWEA.log)

**Comment by ajanauskas** [comment] 2020-08-27 13:45
Issue persists on Xcode 12 beta 6

**Comment by kikettas** [comment] 2020-08-27 14:17
Have the same issue here. The problem seems to be related to `adyen/adyen-3ds2-ios` framework, any plans on uploading the update binary?

**Comment by rachelhyman** [comment] 2020-09-15 17:14
Confirming that this issue still exists on Xcode 12 beta 6. I am using [this Carthage workaround](https://github.com/Carthage/Carthage/issues/3019#issuecomment-692291631) and I get this output when running `carthage update` in a new project:
```
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/rachel.hyman/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189n/adyen-ios/3.6.0/Build/Intermediates.noindex/ArchiveIntermediates/Adyen/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Adyen.framework/Adyen /Users/rachel.hyman/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8189n/adyen-ios/3.6.0/Build/Products/Release-iphonesimulator/Adyen.framework/Adyen -output /Users/rachel.hyman/Desktop/AdyenTest/Carthage/Build/iOS/Adyen.framework/Adyen

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/f2/02p9crh12cj_kbv0xxfgqzj80000gp/T/carthage-xcodebuild.O3s0Nd.log
```

However, the log does indicate that the build succeeded. 

Any updates on a fix or workaround for this issue?

**Comment by descorp** [comment] 2020-09-15 19:49
Thanks, @ajanauskas @kikettas 

Sorry, no updates from our side so far.
We have internal technical complications that prevent us from reproducing it on our end.

Since Xcode 12 release date is upon us, we will speed up the investigation.

So far, I can only recommend trying alternative dependency management solutions.

@rachelhyman , thanks for verifying the Carthage workaround; I have been closely monitoring the situation, and it does not seem like a 100% working solution so far.

> However, the log does indicate that the build succeeded.

This is peculiar...

**Comment by intere** [comment] 2020-09-15 21:41
I have just tried building again using the Xcode 12 GM and it still failing.  It provides even less information in the log though:

Command: `carthage update --platform ios`

Result:
```
*** Fetching adyen-ios
*** Fetching adyen-3ds2-ios
*** Checking out adyen-ios at "3.6.0"
*** Checking out adyen-3ds2-ios at "2.2.0"
*** xcodebuild output can be found in /var/folders/jw/7p44sfp97wn0r9lxqp02d94h0000gn/T/carthage-xcodebuild.HiwYek.log
*** Downloading adyen-3ds2-ios.framework binary at "2.2.0"
*** Building scheme "AdyenCard" in Adyen.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/einternicola/Code/watches/CarthageXcode12Test/Carthage/Checkouts/adyen-ios/Adyen.xcodeproj -scheme AdyenCard -configuration Release -derivedDataPath /Users/einternicola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7208/adyen-ios/3.6.0 -sdk iphonesimulator -destination platform=iOS\ Simulator,id=E1C7E02B-05ED-433C-94D3-C02045DF8640 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/einternicola/Code/watches/CarthageXcode12Test/Carthage/Checkouts/adyen-ios)
```

Log (excerpt):
```
Ld /Users/einternicola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7208/adyen-ios/3.6.0/Build/Intermediates.noindex/Adyen.build/Release-iphonesimulator/AdyenCard.build/Objects-normal/arm64/Binary/AdyenCard normal arm64 (in target 'AdyenCard' from project 'Adyen')
    cd /Users/einternicola/Code/watches/CarthageXcode12Test/Carthage/Checkouts/adyen-ios
    /Applications/Xcode-12-GM.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios10.0-simulator -dynamiclib -isysroot /Applications/Xcode-12-GM.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk -L/Users/einternicola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7208/adyen-ios/3.6.0/Build/Products/Release-iphonesimulator -F/Users/einternicola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7208/adyen-ios/3.6.0/Build/Products/Release-iphonesimulator -FCarthage/Build/iOS -filelist /Users/einternicola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7208/adyen-ios/3.6.0/Build/Intermediates.noindex/Adyen.build/Release-iphonesimulator/AdyenCard.build/Objects-normal/arm64/AdyenCard.LinkFileList -install_name @rpath/AdyenCard.framework/AdyenCard -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/einternicola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7208/adyen-ios/3.6.0/Build/Intermediates.noindex/Adyen.build/Release-iphonesimulator/AdyenCard.build/Objects-normal/arm64/AdyenCard_lto.o -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode-12-GM.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/einternicola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7208/adyen-ios/3.6.0/Build/Intermediates.noindex/Adyen.build/Release-iphonesimulator/AdyenCard.build/Objects-normal/arm64/AdyenCard.swiftmodule -framework Adyen3DS2 -framework Adyen -compatibility_version 1 -current_version 3.6.0 -Xlinker -dependency_info -Xlinker /Users/einternicola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7208/adyen-ios/3.6.0/Build/Intermediates.noindex/Adyen.build/Release-iphonesimulator/AdyenCard.build/Objects-normal/arm64/AdyenCard_dependency_info.dat -o /Users/einternicola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7208/adyen-ios/3.6.0/Build/Intermediates.noindex/Adyen.build/Release-iphonesimulator/AdyenCard.build/Objects-normal/arm64/Binary/AdyenCard
ld: building for iOS Simulator, but linking in dylib built for iOS, file 'Carthage/Build/iOS/Adyen3DS2.framework/Adyen3DS2' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
        Ld /Users/einternicola/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7208/adyen-ios/3.6.0/Build/Intermediates.noindex/Adyen.build/Release-iphonesimulator/AdyenCard.build/Objects-normal/arm64/Binary/AdyenCard normal arm64
(1 failure)
```

**Comment by maksg** [comment] 2020-09-21 13:38
The same error occurs for me when using CocoaPods.

It only happens when building for iOS Simulator but it is possible to fix this temporarily by adding `arm64` to the `Excluded Architectures` in Adyen targets. However this results in being unable to build for a device.

**Comment by descorp** [comment] 2020-09-21 13:40
Hi @maksg 

What version of CocoaPods are you using?

**Comment by maksg** [comment] 2020-09-21 13:45
Hi @descorp 
I'm using `1.9.3` but I've also tried with `1.10.0.rc.1`

**Comment by maksg** [comment] 2020-09-29 14:22
Hey @descorp 

I think that the issue with Cocoapods could be fixed by excluding `arm64` for simulator builds in `.podspec` file.

It was done with Intercom as you can see here: https://github.com/intercom/intercom-ios/pull/385

**Comment by juanuribeo13** [comment] 2020-10-13 16:35
I'm also getting an error on Xcode 12, I tried with version 3.7.0 using cocoapods and get the following `ld: building for iOS Simulator, but linking in dylib built for iOS, file '/.../Pods/Adyen3DS2/Dynamic/Adyen3DS2.framework/Adyen3DS2' for architecture arm64`

**Comment by maksg** [comment] 2020-10-15 08:31
@juanuribeo13, I've discovered recently that if you set `ONLY_ACTIVE_ARCH` parameter to `YES` in your target and pods then it compiles and archives without this error.

You can add this to your Podfile and see if it helps:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
    end
  end
end
```

**Comment by juanuribeo13** [comment] 2020-10-15 13:33
@maksg thank you! this works like a charm 😃

**Comment by richellis** [comment] 2020-10-15 18:55
@descorp here is a Cocoapods thread on the podspec workaround to exclude arm64: https://github.com/CocoaPods/CocoaPods/issues/10065

Adyen will need to add this to both Adyen3DS2 and Adyen podspecs, since Adyen depends on Adyen3DS2. But as noted in that thread and the Intercom example posted above, this is a temporary workaround. As soon as people start using Apple Silicon Macs for development, this is going to cause big problems. Migrating to XCFramework or fixing the binary is the real solution.

The issue I am facing is that I develop a private Cocoapod for my employer, and our pod depends on Adyen. We are unable to publish our pod to our private Cocoapods spec repo because `pod spec lint` fails due to this architecture issue. The workaround we have found is to privately host a copy of the Adyen and Adyen3DS2 podspecs with the workaround added:
```
  # workaround for binary dependencies, see https://github.com/CocoaPods/CocoaPods/issues/10065
  s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
  s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
```
and we have to add this workaround to our private podspec as well.

**Comment by descorp** [comment] 2020-11-24 14:39
3.8.0 is released!
This issue should be fixed now!

**Comment by descorp** [comment] 2020-12-09 11:02
Thanks everyone for feedback and support!
We have added a note in [README](https://github.com/Adyen/adyen-ios#carthage).

I am going to close it for now.
Feel free to provide any additional feedback in this thread or create a new one is necessary.

**Closed by descorp** 2020-12-09 11:02 UTC
Labels: awaiting feedback

**Comment by khawarcareem** [comment] 2021-03-03 13:20
@descorp Hi, am having issue in running Unit tests while having "Ayden" pod, issue am facing is this?
<img width="480" alt="Screenshot 2021-03-03 at 6 19 14 PM" src="https://user-images.githubusercontent.com/73534982/109811696-fd106180-7c4c-11eb-825c-fb36727b8a6b.png">
Build is successful but when unit tests starts running, it got failed.
