### ISSUE TITLE
Build an react-native app that uses Adyen IOS SDK in Macbook M1

### ISSUE THREAD

**Issue by vitorbetani** [Adyen/adyen-ios#516] opened 2021-05-26 19:10 UTC
**Describe the challenge**
I'm trying to build my client app with a MAC M1 and keep getting the error
**Could not find module 'Adyen' for target 'arm64-apple-ios-simulator';**

I've tried to remove the Adyen from Cocoapods and add to SPM, but still no success.

Is important to remind that I can't remove cocoapods completely because is a react native project and cocoapods is used for all linked libraries in the project. 
Also, I'm not 100% familiar with Xcode, just enough to get things done.

I use the following versions: 
Xcode 12.5
IOS 14.5

This project works fine in non-M1 chips.

**What steps did you take?**
1. Remove the references of Adyen pod in Build phases > Copy Pods Resources > Input Files
2. Add the Adyen 3.8.2 in SPM and link in Build Phases > Link Binary with Libraries

**What is the expected behavior / API ?**
To successfully build the app in the MAC M1

**Comment by descorp** [comment] 2021-05-27 08:16
Hey @vitorbetani 

Thanks for reaching out!

Indeed M1 is an unexplored territory for everyone :)
What is the error you facing?

**Comment by descorp** [comment] 2021-05-27 17:15
hm.. SPM supposed to work on M1.

Could you try to make a blank project with only SPM and Adyen?
I am wandering if this is some sort of a conflict between SPM and Cocoapods..

**Comment by vitorbetani** [comment] 2021-05-27 17:51
For sure,
I’ll do it and answer you with the results in the nexts days
Em 27 de mai. de 2021 14:15 -0300, Vladimir Abramichev ***@***.***> escreveu:

**Comment by descorp** [comment] 2021-06-11 11:13
Hey @vitorbetani 

How is it going?
were you able to resolve the problem?

**Comment by vitorbetani** [comment] 2021-06-13 00:11
Hey Vladimir,

Just to let register, I was only able to do it running with arch -x86_64  or using rosetta.

Any other try outs with m1 didn’t work at all.



Em 11 de jun. de 2021 08:13 -0300, Vladimir Abramichev ***@***.***>, escreveu:

**Comment by VaslD** [comment] 2021-07-16 09:49
The root cause is exclusion of architecture ARM64 when compiling for Simulator in Podspec:

```
  s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64', 'SWIFT_SUPPRESS_WARNINGS' => 'YES' }
  s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
```

Is there a reason that these settings must be set as is? I don't see this on any other CocoaPods I depend on.

**Comment by descorp** [comment] 2021-07-16 13:47
Hey @VaslD 

It was added with introduction of Xcode 12 to solve [issue with non M1 laptops](https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios) by simply excluding the `arm64`
With the increasing number of M1 users, this solution becomes less and less suitable.

We will verify other [possible solutions](https://stackoverflow.com/posts/63714000/revisions).

Thanks for feedback!

**Comment by VaslD** [comment] 2021-07-16 15:56
I see. But as other answers to the same SO question have pointed out, this solution should only be used as a temporary fix. I personally think it should never be set in the published Podspec because it makes the entire client project M1-incompatible.

At the very least it should only be set for Release builds. Because according to various answers, Debug builds have “Build for Active Architecture” on by default which only builds one architecture at each run so it would never trigger this multi-arch problem. Also people rarely run Release on simulators. Now this seems like a win-win.

**Comment by descorp** [comment] 2021-07-19 12:44
Hey @VaslD 

You absolutely right.
We will re-evaluate this solution ASAP.

**Comment by descorp** [comment] 2021-09-07 13:59
Hey @VaslD @vitorbetani 

v4.1.0 is released. 
Could you verify that is solves issues with M1 laptops?

**Comment by descorp** [comment] 2021-09-21 14:40
I am going to close this ticket for now.
Please feel free to reopen if necessary.

**Closed by descorp** 2021-09-21 14:40 UTC
