### ISSUE TITLE
[NEED ASSIST]  "Secure channel setup failed." com.adyen.Adyen3DS2.ADYRuntimeError Code=1

### ISSUE THREAD

**Issue by Jack25apr** [Adyen/adyen-ios#730] opened 2021-12-09 07:18 UTC
Hello,
We got successfully implemented test environment (iOS Drop-in + our "proxy"-backend)
[iOS, Adyen (4.5.0), Adyen3DS2 (2.2.4)]

Then we wanted to test as much as possible in live.

During testing in live with live card 5168 **** **** **** (not stored method, just newly entered)
I've got the next code after testing in live environment inside Framework:
com.adyen.Adyen3DS2.ADYRuntimeError Code=1 "Secure channel setup failed."

I cant go deeper - internals are hidden the framework.

(Some live card gave success - "no funds" - thats ok).

The last request as I can see with Charles (error persists on that card without proxy-tool ):

https://checkoutshopper-live.adyen.com/checkoutshopper/v1/submitThreeDS2Fingerprint?clientKey=live_H**********S

Request:
{ "clientKey": "live_HS", "fingerprintResult": "e*******9", "paymentData": "Ag***************==" }

Response: 200

{ "action": { "authorisationToken": "Ab******=", "subtype": "challenge", "token": "ey*******==", "type": "threeDS2" }, "type": "action" }

Any ideas ?

**Comment by descorp** [comment] 2021-12-09 09:46
Hey @Jack25apr 

What version of Adyen API are you using?

Could you share the `pspReference` with me via email vladimir.abramichev@adyen.com ?
You should be able to find it in headers of `/payments` response

**Comment by descorp** [comment] 2021-12-13 09:18
As discussed in dm, the issue was caused by misconfiguration on Issuing bank side.
I am going to close this ticket for now.
Feel free to continue in this thread or reopen it in necessary.

**Closed by descorp** 2021-12-13 09:18 UTC
